call ./install.bat net.tocollege gwt_maven 1.0.1  gwt_maven-1.0.1.jar
call ./install.bat com.google gwt-incubator 0.0.1.build591 gwt-incubator-0.0.1.build591.jar
call ./install.bat com.google gwt-google-apis 1.5.0.build235 gwt-google-apis-1.5.0.build235.jar
call ./install.bat com.allen_sauer.gwt.dnd gwt-dnd 2.0.7 gwt-dnd-2.0.7.jar
call ./install.bat com.allen_sauer.gwt.log gwt-log 1.5.6 gwt-log-1.5.6.jar
call ./install.bat javax.transaction jta 1.0.1B jta-1.0.1B.jar
call ./install.bat org.opensymphony compass 1.2.0 compass-1.2.0.jar
call ./install.bat javax.servlet jstl 1.2 jstl-1.2.jar
call ./install.bat com.sun.xml jaxb-impl 2.1 jaxb-impl-2.1.jar
call ./install.bat javax.xml.bind jaxb-api 2.1 jaxb-api-2.1.jar
call ./install.bat com.facebook.api facebook-java-api 1.7.4 facebook-java-api-1.7.4.jar
