package com.apress.progwt.client.domain;

//Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.apress.progwt.client.domain.generated.AbstractUser;

/**
 * User generated by hbm2java
 */

/**
 * Extended by ServerSideUser on the Server to implement UserDetails,
 * Since getting the acegisecurity jar into client side land was a no go.
 * 
 */
public class User extends AbstractUser implements Serializable, Loadable {

    public User() {
        setEnabled(true);
        setSupervisor(false);

    }

    public boolean isAccountNonExpired() {
        return true;
    }

    public boolean isAccountNonLocked() {
        return true;
    }

    public boolean isCredentialsNonExpired() {
        return true;
    }

    // @Override
    public String toString() {
        return "|" + getId() + ":" + getUsername() + "|";
    }

    /**
     * TODO PEND HIGH
     */
    public String getNickname() {
        if (isOpenID()) {
            String half = getUsername().replaceAll("http://", "");
            return half.replaceAll("/", "");
        }
        return getUsername();
    }

    private boolean isOpenID() {
        return getPassword() == null;
    }

    public void addRanked(Application schoolAndAppProcess) {
        schoolAndAppProcess.setUser(this);
        getSchoolRankings().add(schoolAndAppProcess);
    }

    public void addRanked(int rank, Application sap) {
        sap.setUser(this);
        getSchoolRankings().remove(sap);
        getSchoolRankings().add(rank, sap);
    }

    public int getPriority(RatingType ratingType) {
        Integer priority = getPriorities().get(ratingType);
        if (priority == null) {
            return 5;
        }
        return priority;
    }

    public List<ApplicationAndScore> getPrioritizedRankings() {
        List<ApplicationAndScore> rtn = new ArrayList<ApplicationAndScore>();

        for (Application application : getSchoolRankings()) {
            rtn.add(application.getAppAndScore(getRatingTypes(), this));
        }

        Collections.sort(rtn);

        return rtn;
    }

}
